# Generated by Django 3.0.5 on 2020-04-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('jeopardy_questions', models.FileField(upload_to='')),
                ('jeopardy_answers', models.FileField(upload_to='')),
                ('double_jeopardy_questions', models.FileField(upload_to='')),
                ('double_jeopardy_answers', models.FileField(upload_to='')),
            ],
        ),
    ]
