# Generated by Django 3.0.5 on 2020-04-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20200425_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='final_answer',
            field=models.CharField(default="This game doesn't appear to have a final jeopardy", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='final_category',
            field=models.CharField(default="This game doesn't appear to have a final jeopardy", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='final_clue',
            field=models.CharField(default="This game doesn't appear to have a final jeopardy", max_length=500),
            preserve_default=False,
        ),
    ]
