# Generated by Django 3.0.5 on 2020-04-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20200426_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='This game has no name', max_length=150),
            preserve_default=False,
        ),
    ]
