# Generated by Django 3.0.5 on 2020-05-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
