# Generated by Django 3.0.6 on 2020-05-09 01:04

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_game_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='double_jeopardy_answers',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='double_jeopardy_questions',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='jeopardy_answers',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='jeopardy_questions',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
